
services:
  relational_db:
    image: postgres:15-alpine
    container_name: dr_siem_pg
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: dr_siem_clickhouse
    restart: always
    ports:
      - "8123:8123"      
    volumes:
      - ch_data:/var/lib/clickhouse
      - ch_logs:/var/log/clickhouse-server

  app:
    image: node:18-alpine
    container_name: dr_siem_backend
    restart: always
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    ports:
      - "443:8443"       
      - "514:514/udp"    
    environment:
      PG_HOST: relational_db
      PG_USER: ${POSTGRES_USER}
      PG_PASSWORD: ${POSTGRES_PASSWORD}
      PG_NAME: ${POSTGRES_DB}
      CH_HOST: http://clickhouse:8123
    depends_on:
      - relational_db
      - clickhouse
    command: sh -c "npm install && node server.js"

volumes:
  pg_data:
  ch_data:
  ch_logs:
